db:
  image: mysql
  volumes:
    - ~/.docker-volumes/openproject/db:/var/lib/mysql
  expose:
    - "3306"
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=true

worker: &ruby
  build: .
  volumes:
    - .:/usr/src/app
  links:
    - db
  environment:
    - "DATABASE_URL=mysql2://root@db/openproject_development?encoding=utf8"
    - "RAILS_CACHE_STORE=file_store"
  command: "./docker/worker"

web:
  <<: *ruby
  ports:
    - "8080:8080"
  command: "./docker/web"

frontend:
  build: .
  volumes:
    - .:/usr/src/app
  command: "./docker/webpack-watch"
